#!/bin/sh

while :
do
    ./cmake-for-x86.sh
    stack build
    make # stack build --ghc-options=-ferror-spans
    # nohup ./make-doc.sh > /dev/null  2>&1 &
    inotifywait -e modify -r ./src/ ./exe-src/ ./examples/ formura.cabal
done

# http://stackoverflow.com/questions/32712775/generating-documentation-for-my-own-code-with-haddock-and-stack
