#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='xeon_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def options(opt):
        opt.load('compiler_cxx')

def configure(conf):
        conf.load('compiler_cxx')
	conf.check(header_name='stdio.h', features='cxx cxxprogram', mandatory=False)

def build(bld):
	bld(features='cxx cxxprogram',source='main.cpp', target='app', use='mylib',includes=['.'],cxxflags=['-std=c++11', '-O3', '-Wall', '-mcmodel=large'])
	bld.stlib(target='mylib', source='a.cpp')


	if bld.cmd != 'clean':
		from waflib import Logs
		bld.logger = Logs.make_logger('test.log', 'build') # just to get a clean output
		bld.logger = None
