#!/bin/bash
./configure --host=sparc64 CXX=mpiFCCpx CC=mpifccpx \
            CFLAGS="-O3 -Kfast,parallel  -Kocl -Koptmsg=2 -Karray_private -Kinstance=8 -Kdynamic_iteration -Kloop_fission -Kloop_part_parallel -Keval -Kreduction" \
            CXXFLAGS="-O3 -Kfast,parallel  -Kocl -Koptmsg=2 -Karray_private -Kinstance=8 -Kdynamic_iteration -Kloop_fission -Kloop_part_parallel -Keval  -Kreduction"

